[package]
name = "robusta-android-example"
version = "0.2.2"
authors = ["Elise Chouleur"]
edition = "2018"

[lib]
name = "robustaandroidexample"
crate-type = ["cdylib"]

[dependencies]
robusta_jni = { path = "../.", version = "0.2" }
jni = "^0.20"
android_logger = "^0"
log = "^0"
