name: Java setup, build and test

on:
  workflow_call:

jobs:
  desktop-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Add $JAVA_HOME to library path
        if: runner.os == 'Linux'
        run:   |
         echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/lib:$JAVA_HOME/lib/server" >> "$GITHUB_ENV"

      - name: Add $JAVA_HOME to library path
        if: runner.os == 'macOS'
        run:   |
         echo "DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:$JAVA_HOME/lib:$JAVA_HOME/lib/server" >> "$GITHUB_ENV"

      - name: Add $JAVA_HOME to library path
        if: runner.os == 'Windows'
        run:   |
         Add-Content $env:GITHUB_PATH "$env:JAVA_HOME\bin;$env:JAVA_HOME\bin\server"

#      - name: Debug session
#        uses: mxschmitt/action-tmate@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose -- --test-threads=1

  android-build-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build Android example
        run: cargo build --package robusta-android-example --verbose
